# Hack to use the latest version instead of the gems when developing Mirah
if File.exist?('../../lib/mirah.rb')
  $: << File.expand_path('../../lib')
end
if File.exist?('../../../bitescript/lib/bitescript.rb')
  $: << File.expand_path('../../../bitescript/lib/')
end
require 'mirah/appengine_tasks'

appengine_app :app

DUBY_APP = "#{Duby.dest_path}/org/mirah/wiki/MirahWiki.class"
Templates = Dir.glob("#{Duby.source_path}/org/mirah/wiki/*.eduby.html")

Rake::Task[DUBY_APP].enhance(Templates)

task :app => DUBY_APP
task :default => :server
