# Hack to use the latest version instead of the gems when developing Mirah
if File.exist?('../../lib/mirah.rb')
  $: << File.expand_path('../../lib')
end
if File.exist?('../../../bitescript/lib/bitescript.rb')
  $: << File.expand_path('../../../bitescript/lib/')
end
require 'mirah/appengine_tasks'

appengine_app :app

MIRAH_APP = "#{Mirah.dest_path}/org/mirah/MirahApp.class"
LIST = "#{Mirah.source_path}/org/mirah/list.dhtml"

# We want to recompile the app if the template gets modified
Rake::Task[MIRAH_APP].enhance([LIST])

task :app => MIRAH_APP
task :default => :server
