#!/bin/bash

# mirah/tools$ ./gen_authors.sh
# Add organization names manually.

cat <<EOF > ../NOTICE
# This file is automatically generated from the git commit history
# by tools/gen_authors.sh.

$(git log --pretty=format:"%aN <%aE>" | sort | uniq)
EOF
